Sprint7
ClevertecFrontendLab/MuJlblii pull request #5
Opened 2023-03-25 22:50 UTC by MuJlblii

2023-03-25 23:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679785311/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-25 23:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679786140/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)

2023-03-25 23:57 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679788677/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)

2023-03-26 10:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828088/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 11:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679828857/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-26 11:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679829859/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)

2023-03-26 12:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679833034/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 14:48 UTC, vvikota requested changes

2023-03-26 14:48 UTC, vvikota commented on src/components/booking/booking.tsx
> +    const {User} = useSelector((state: UserStateType) => state.user)
селекторы лучше создавать в сторе в отдельном файлике, а в компоненте только использовать: 
const user= useAppSelector(userSelector), а остальное будет в сторе

2023-03-26 14:48 UTC, vvikota commented on src/components/header/header.tsx
> +                    ? <img className={style.header__avatar} src={`https://strapi.cleverland.by${userProfile.avatar}`} alt="Avatar" />
`https://strapi.cleverland.by - вот это нужно поместить в константу

2023-03-26 14:48 UTC, vvikota commented on src/layouts/layout/layout.tsx
> +                isLoadingCategories
сложные условие помещаем в константы, до return

2023-03-26 14:48 UTC, vvikota commented on src/pages/book/comment-modal/comment-modal.tsx
> +            // createdAt: dayjs().add(3, 'hour').toISOString(),
удаляем комменты

2023-03-26 14:48 UTC, vvikota commented on src/pages/book/comment/comment.tsx
> +                <img className={style.avatar_img} src={user.avatarUrl ? `https://strapi.cleverland.by${user.avatarUrl}` : logo} alt='Logo' />
вот https://strapi.cleverland.by, которое уже можно было достать из константы)

2023-03-26 14:48 UTC, vvikota commented on src/pages/profile/credentials/credentials.module.css
> +    /* grid-template-columns: repeat(2, 3fr); */
комменты удаляем , посмотрите по всему приложению

2023-03-26 14:48 UTC, vvikota commented on src/pages/profile/credentials/credentials.tsx
> +        const result = clearArrValueFields.reduce((obj, element) => ({ ...obj, [element[0]]: element[1] }), {})
такие вот штуки с абстрактной логикой нужно помещать в utils и выносить из компонента

2023-03-26 14:48 UTC, vvikota commented on src/pages/profile/profile-bookcard/profile-bookcard.tsx
> +    const ratingStars = (rate: number | null) => {
вот это по хорошему бы вынести в отдельный компонент и переиспользовать

2023-03-26 17:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679853165/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 18:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679855294/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 18:42 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679856165/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-26 19:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679857362/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 20:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679861891/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20success%20(failed).png)

2023-03-26 20:42 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679863330/9-app%20-burger-menu-close-768px.png)

2023-03-27 01:08 UTC, ValadzkoAliaksei commented on src/components/comment-modal/comment-modal.tsx
> +            dispatch(setToasterMsg({type: 'success', message: 'Спасибо, что нашли время изменить оценку!'}))
Можно создать  1 тост на весь проект, такой же. просто он появляется от стейта например isShowToast и принимает на себя type = error || success и text/
В нем сет таймАут на 4 секунды вроде и он делает isShowToast = false

2023-03-27 01:08 UTC, ValadzkoAliaksei commented on src/layouts/layout/layout.tsx
> +        || isLoadingChangeProfile;
лоадинг тоже можно  было 1 сделать. Представьте если бы было 100 запросов?)

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/61273546/227817660-690154c3-146a-4b5c-9c3e-eeacf51bdf02.png)
Если нет  аватарки - то котик

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +import { PATHS } from '../constants/path-routing';
![image](https://user-images.githubusercontent.com/61273546/227817751-607ac52f-547c-4904-bc9b-69191a9570c9.png)
Должна быть желтенькая

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +import { BookType, BookPageType, BooksStateType, CategoriesType, CommentsType } from '../types/types';
![image](https://user-images.githubusercontent.com/61273546/227817853-1fd6e1dd-bb19-449e-b3db-4b0d0a6474d1.png)
Что-то верстка поехала на айфоне(

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +type CommentTypePost = {
![image](https://user-images.githubusercontent.com/61273546/227817928-918c5f68-3c71-43e2-a28f-3392a3d9d69b.png)
и слайдер кривой... это все профиль

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +  bookId: number,
![image](https://user-images.githubusercontent.com/61273546/227818102-5cd1a36c-a270-4402-a9f7-01bcf7817cb3.png)
При изменении бронирования выбираешь тот же самый день и получаешь ошибку на беке, что так делать нельзя)

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +  toSend: {data: {rating: number, text: string, user: number, book: number}},
![image](https://user-images.githubusercontent.com/61273546/227818266-e9160b70-1ed1-4a58-9f55-12641b6ef3ae.png)
изменение брони в книге по id не правильная строка. нет ID

2023-03-27 01:18 UTC, ValadzkoAliaksei commented on src/app/api.ts
> +  backupComment: CommentsType,
![image](https://user-images.githubusercontent.com/61273546/227818388-967e23d6-c547-446a-af2f-341f77e2ef02.png)
При переходе между страницами. бургер должен закрываться

2023-03-27 10:57 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- search -- clearing search input (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/Sprint%204%20--%20search%20and%20sort%20--%20search%20--%20clearing%20search%20input%20(failed).png)
***
**Sprint 4 -- search and sort -- sort -- sort should be asc (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/Sprint%204%20--%20search%20and%20sort%20--%20sort%20--%20sort%20should%20be%20asc%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- add-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20add-review%20--%20fail%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MuJlblii/1679914673/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-27 11:32 UTC, ValadzkoAliaksei approved these changes

2023-03-27 11:33 UTC, vvikota approved these changes

2023-03-27 11:36 UTC, merged